name: GitHub Actions Build

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    defaults:
      run:
        shell: ${{ matrix.platform.shell }}

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Windows,         os: windows-latest, artifact: 'ags-windows', shell: cmd, bindir: "build/Release", runbin: ".\\ags.exe", catcmd: type }
        - { name: Ubuntu,          os: ubuntu-latest,  artifact: 'ags-linux',   shell: sh,  bindir: "build", runbin: "./ags", catcmd: cat                          }
        - { name: macOS,           os: macos-latest,   artifact: 'ags-macos',   shell: sh,  bindir: "build", runbin: "./ags", catcmd: cat                          }

    steps:    
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: |
        cmake --version
        cmake -S "${{github.workspace}}" -B "${{github.workspace}}/build" -DAGS_BUILD_TOOLS=1 -DAGS_TESTS=1 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build "${{github.workspace}}/build" --config ${{env.BUILD_TYPE}} --parallel 2

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
            
    - name: TAP Test
      working-directory: ${{github.workspace}}/${{matrix.platform.bindir}}
      run: |
        curl -sLo tap_demo.ags https://github.com/ericoporto/tap/releases/download/0.1.0/tap_demo.ags
        ${{matrix.platform.runbin}} --user-data-dir . tap_demo.ags
        ${{matrix.platform.catcmd}} agstest.log
        
    - uses: ericoporto/tap-summary@v1.0.1
      with:
        path: ${{github.workspace}}/${{matrix.platform.bindir}}/agstest.log

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.platform.artifact }}
        path: |
          ${{github.workspace}}/build/${{env.BUILD_TYPE}}/ags.exe
          ${{github.workspace}}/build/ags
          ${{github.workspace}}/build/ags.exe